apiVersion: apps/v1
kind: Deployment
metadata:
  name: brownbagnx-backend-deployment
spec:
  selector:
    matchLabels:
      app: brownbagnx
      tier: brownbagnx-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: brownbagnx
        tier: brownbagnx-backend
    spec:
      containers:
      - name: brownbagnx
        image: mateuszbrycki/brownbagnx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http