apiVersion: apps/v1
kind: Deployment
metadata:
  name: brownbagnx
spec:
  selector:
    matchLabels:
      app: brownbagnx
  replicas: 2
  template:
    metadata:
      labels:
        app: brownbagnx
    spec:
      containers:
      - name: brownbagnx
        image: mateuszbrycki/brownbagnx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http

---
apiVersion: v1
kind: Service
metadata:
  name: brownbagnx-service
  labels:
    app: brownbagnx
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: brownbagnx
    tier: brownbagnx
  type: LoadBalancer
